### PR TITLE
add documentation and golint

### LINKED ISSUE #16: Add the code comments, documetation and golint
Hi,

This is an exciting project. I wanted to go through the entire codebase and while doing so I found that it requires some code comments and documentation.

### PR DESCRIPTION
**Pull request by pallavJha**
- Fixes #16

### CODE REVIEW

**Comment by eatonphil** [comment]
Thanks! This is going to conflict with a PR I have in progress (#15). So I'll commit to this branch after I merge that PR.

I don't find it very useful to have comments that are no more explanative than the struct or function name (e.g. SelectStatement, statementKind, etc.) so I will remove those. But other than that there are some good additions here.

**Comment by eatonphil** [comment]
I see now that golint requires all these to be documented. In that case, fine.

**Comment by eatonphil** [comment]
Ok, after looking into things a little bit more I decided to go with just golangci-lint for now which is a little more configurable and I've used it in the past.

Some of these comments could still be useful, but I'd leave that up to you.

If you'd like to get the PR approved I'd say:

1. Drop the golint
2. Remove any comments that are super obvious

Thanks for the effort!

**Comment by pallavJha** [comment]
Hi @eatonphil 

I've removed the `golint` and tested with the `golangci-lint` after resolving conflicts and merging with master.

**Comment by eatonphil** [comment]
Made a few changes but looks good. Thank you!

**Pull request merged**
